name: Run Affiliate Blog Bot

on:
  schedule:
    - cron: '0 9 * * *'   # 9 AM UTC
    - cron: '0 14 * * *'  # 2 PM UTC
    - cron: '0 19 * * *'  # 7 PM UTC
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
      WORDPRESS_URL: ${{ secrets.WORDPRESS_URL }}
      WORDPRESS_USERNAME: ${{ secrets.WORDPRESS_USERNAME }}
      WORDPRESS_PASSWORD: ${{ secrets.WORDPRESS_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run bot
        run: python main.py

